name: Bug report
description: Report a bug in L-Bot
labels: [bug]
body:
  - type: textarea
    id: expected
    attributes: { label: Expected behavior }
  - type: textarea
    id: actual
    attributes: { label: Actual behavior / logs }
  - type: textarea
    id: steps
    attributes: { label: Steps to reproduce }
