name: Apply patch v2
on:
  issue_comment:
    types: [created]
permissions:
  contents: write
  pull-requests: read

jobs:
  apply:
    # ต้องมี /apply-patch ในคอมเมนต์
    if: contains(github.event.comment.body, '/apply-patch')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract patch from comment
        id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.comment.body;

            // 1) พยายามจับ ```patch / ```diff ก่อน
            let m = body.match(/```(?:patch|diff)\r?\n([\s\S]*?)\r?\n```/m);

            // 2) ถ้าไม่เจอ ให้รับ code block ธรรมดาก็ได้
            if (!m) m = body.match(/```\r?\n([\s\S]*?)\r?\n```/m);

            if (!m) {
              core.setFailed('No fenced code block found in the comment.');
            } else {
              core.setOutput('patch', m[1]);
            }

      - name: Save patch file
        run: |
          printf "%s" "${{ steps.extract.outputs.patch }}" > change.patch
          echo "----- preview -----"
          head -n 30 change.patch || true

      - name: Apply patch
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git apply -p0 change.patch

      - name: Commit & push
        run: |
          git add -A
          git commit -m "apply-patch from issue #${{ github.event.issue.number }} by @${{ github.actor }}"
          git push
