name: Apply patch v4 (robust)
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    if: contains(github.event.comment.body, '/apply-patch')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract patch from comment (robust)
        id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.comment.body || '';
            // 1) ```patch / ```diff
            let m = body.match(/^[>\s]*```(?:patch|diff)\s*\r?\n([\s\S]*?)\r?\n[>\s]*```/im);
            // 2) fallback: fenced code block ใดๆ
            if (!m) m = body.match(/^[>\s]*```\s*\r?\n([\s\S]*?)\r?\n[>\s]*```/im);
            if (!m) core.setFailed('No fenced code block found in the comment.');
            else core.setOutput('patch', m[1]);

      - name: Save patch to file
        run: |
          printf "%s" "${{ steps.extract.outputs.patch }}" > change.patch
          echo "---- patch preview (first 30 lines) ----"
          head -n 30 change.patch || true

      - name: Apply patch
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git apply -p0 --whitespace=nowarn change.patch
          git status --porcelain

      # ใช้ action สำเร็จรูปในการสร้าง branch/commit/push และเปิด PR ให้เอง
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: |
            apply-patch from issue #${{ github.event.issue.number }} by @${{ github.actor }}
          branch: patch/apply-${{ github.run_id }}
          title: Apply patch from issue #${{ github.event.issue.number }}
          body: |
            Created by workflow. Actor: @${{ github.actor }}.
          base: main
          signoff: false
          delete-branch: true
