name: L-Bot CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Quick backtest
        run: |
          python backtests/run_quick_backtest.py --minutes 5000 --symbol XAUUSD > backtests/out.txt
      - name: Parse metrics
        run: python backtests/print_metrics.py backtests/out.txt > metrics.txt
      - name: Enforce gate
        run: python backtests/enforce_gate.py --maxdd 0.25 --min_sharpe 1.2 metrics.txt
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: lbot-report
          path: |
            backtests/out.txt
            metrics.txt