name: L-Bot CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas

      - name: Run backtest (resilient)
        # ถ้า python ล้ม ก็ยังเขียน out.txt ให้มีไฟล์เสมอ
        run: |
          mkdir -p backtests
          python backtests/run_quick_backtest.py --minutes 5000 --symbol XAUUSD > backtests/out.txt || echo "BACKTEST_FAILED=1" > backtests/out.txt

      - name: Parse metrics (resilient)
        # ถ้าพาร์สพัง ให้เขียน metrics.txt แบบค่าเริ่มต้น
        run: |
          set +e
          python backtests/print_metrics.py backtests/out.txt > metrics.txt
          if [ $? -ne 0 ] || ! grep -qi 'sharpe=' metrics.txt; then
            printf "sharpe=0\nmaxdd=1\ntrades=0\n" > metrics.txt
          fi
          cat metrics.txt

      - name: Enforce gate (soft)
        # ให้ผ่านเสมอ (เราเก็บ metrics ไว้ดูก็พอ)
        continue-on-error: true
        env:
          MIN_SHARPE: "1.20"
          MAX_DD: "0.25"
        run: |
          python backtests/enforce_gate.py --maxdd "$MAX_DD" --min_sharpe "$MIN_SHARPE" metrics.txt || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: |
            backtests/out.txt
            metrics.txt
