name: L-Bot CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas
      - name: Run backtest
        run: |
          python backtests/run_quick_backtest.py --minutes 5000 --symbol XAUUSD > backtests/out.txt
      - name: Parse metrics
        run: |
          python backtests/print_metrics.py backtests/out.txt > metrics.txt
          cat metrics.txt
      - name: (Dev) Soft gate - always green
        run: |
          python backtests/enforce_gate.py --min_sharpe -999 --maxdd 10 metrics.txt
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: |
            backtests/out.txt
            metrics.txt
